import type { SiteSnapshot } from "../types.js";

export const jaUncyclopediaSnapshot: SiteSnapshot = {
  id: "uncyc_ja",
  capturedAt: "2026-04-25T03:59:12Z",
  generator: "MediaWiki 1.39.3",
  phpVersion: "8.3.6",
  lang: "ja",
  timezone: "Asia/Tokyo",
  server: "https://ansaikuropedia.org",
  articlePath: "/wiki/$1",
  scriptPath: "",
  mainPage: "メインページ",
  namespaces: {
    "-2": { id: -2, name: "メディア", canonical: "Media", case: "first-letter" },
    "-1": { id: -1, name: "特別", canonical: "Special", case: "first-letter", subpages: true },
    0: { id: 0, name: "", case: "first-letter", content: true },
    1: { id: 1, name: "トーク", canonical: "Talk", case: "first-letter", subpages: true },
    2: { id: 2, name: "利用者", canonical: "User", case: "first-letter", subpages: true },
    3: {
      id: 3,
      name: "利用者・トーク",
      canonical: "User talk",
      case: "first-letter",
      subpages: true
    },
    4: {
      id: 4,
      name: "Uncyclopedia",
      canonical: "Project",
      case: "first-letter",
      subpages: true
    },
    5: {
      id: 5,
      name: "Uncyclopedia・トーク",
      canonical: "Project talk",
      case: "first-letter",
      subpages: true
    },
    6: { id: 6, name: "ファイル", canonical: "File", case: "first-letter" },
    7: {
      id: 7,
      name: "ファイル・トーク",
      canonical: "File talk",
      case: "first-letter",
      subpages: true
    },
    8: {
      id: 8,
      name: "MediaWiki",
      canonical: "MediaWiki",
      case: "first-letter",
      subpages: true
    },
    9: {
      id: 9,
      name: "MediaWiki・トーク",
      canonical: "MediaWiki talk",
      case: "first-letter",
      subpages: true
    },
    10: { id: 10, name: "テンプレート", canonical: "Template", case: "first-letter", subpages: true },
    11: {
      id: 11,
      name: "テンプレート・トーク",
      canonical: "Template talk",
      case: "first-letter",
      subpages: true
    },
    12: { id: 12, name: "ヘルプ", canonical: "Help", case: "first-letter", subpages: true },
    13: { id: 13, name: "ヘルプ・トーク", canonical: "Help talk", case: "first-letter", subpages: true },
    14: { id: 14, name: "カテゴリ", canonical: "Category", case: "first-letter" },
    15: {
      id: 15,
      name: "カテゴリ・トーク",
      canonical: "Category talk",
      case: "first-letter",
      subpages: true
    },
    32: { id: 32, name: "Portal", canonical: "Portal", case: "first-letter" },
    33: { id: 33, name: "Portal talk", canonical: "Portal talk", case: "first-letter" },
    102: { id: 102, name: "UnNews", canonical: "UnNews", case: "first-letter" },
    103: { id: 103, name: "UnNews talk", canonical: "UnNews talk", case: "first-letter" },
    104: { id: 104, name: "Undictionary", canonical: "Undictionary", case: "first-letter" },
    105: {
      id: 105,
      name: "Undictionary talk",
      canonical: "Undictionary talk",
      case: "first-letter"
    },
    106: { id: 106, name: "Game", canonical: "Game", case: "first-letter" },
    107: { id: 107, name: "Game talk", canonical: "Game talk", case: "first-letter" },
    110: { id: 110, name: "Forum", canonical: "Forum", case: "first-letter" },
    111: { id: 111, name: "Forum talk", canonical: "Forum talk", case: "first-letter" },
    112: { id: 112, name: "UnTunes", canonical: "UnTunes", case: "first-letter" },
    113: { id: 113, name: "UnTunes talk", canonical: "UnTunes talk", case: "first-letter" },
    116: { id: 116, name: "UnBooks", canonical: "UnBooks", case: "first-letter" },
    117: { id: 117, name: "UnBooks talk", canonical: "UnBooks talk", case: "first-letter" },
    710: { id: 710, name: "TimedText", canonical: "TimedText", case: "first-letter" },
    711: { id: 711, name: "TimedText talk", canonical: "TimedText talk", case: "first-letter" },
    828: { id: 828, name: "モジュール", canonical: "Module", case: "first-letter", subpages: true },
    829: {
      id: 829,
      name: "モジュール・トーク",
      canonical: "Module talk",
      case: "first-letter",
      subpages: true
    },
    2300: { id: 2300, name: "Gadget", canonical: "Gadget", case: "case-sensitive" },
    2301: { id: 2301, name: "Gadget talk", canonical: "Gadget talk", case: "case-sensitive" },
    2302: {
      id: 2302,
      name: "Gadget definition",
      canonical: "Gadget definition",
      case: "case-sensitive"
    },
    2303: {
      id: 2303,
      name: "Gadget definition talk",
      canonical: "Gadget definition talk",
      case: "case-sensitive"
    }
  },
  namespaceAliases: {
    media: -2,
    "メディア": -2,
    special: -1,
    "特別": -1,
    talk: 1,
    "トーク": 1,
    "ノート": 1,
    user: 2,
    "利用者": 2,
    "user talk": 3,
    "利用者・トーク": 3,
    "利用者‐会話": 3,
    project: 4,
    uncyclopedia: 4,
    "uncyclopedia‐ノート": 5,
    file: 6,
    image: 6,
    "ファイル": 6,
    "画像": 6,
    "file talk": 7,
    "image talk": 7,
    "ファイル・トーク": 7,
    "ファイル‐ノート": 7,
    "画像‐ノート": 7,
    mediawiki: 8,
    "mediawiki・トーク": 9,
    "mediawiki‐ノート": 9,
    template: 10,
    "テンプレート": 10,
    "template talk": 11,
    "テンプレート・トーク": 11,
    "template‐ノート": 11,
    help: 12,
    "ヘルプ": 12,
    "help talk": 13,
    "ヘルプ・トーク": 13,
    "help‐ノート": 13,
    category: 14,
    "カテゴリ": 14,
    "category talk": 15,
    "カテゴリ・トーク": 15,
    "category‐ノート": 15,
    module: 828,
    "モジュール": 828
  },
  extensions: [
    { name: "MultiMaps", type: "parserhook", version: "0.7.3" },
    { name: "CategoryTree", type: "parserhook", version: null },
    { name: "Cite", type: "parserhook", version: null },
    { name: "EmbedVideo", type: "parserhook", version: "2.8.0" },
    { name: "ImageMap", type: "parserhook", version: null },
    { name: "InputBox", type: "parserhook", version: "0.3.0" },
    { name: "ParserFunctions", type: "parserhook", version: "1.6.0" },
    { name: "Poem", type: "parserhook", version: null },
    { name: "SyntaxHighlight", type: "parserhook", version: "2.0" },
    { name: "TemplateStyles", type: "parserhook", version: "1.0" },
    { name: "Variables", type: "parserhook", version: "2.5.1" },
    { name: "SimpleMathJax", type: "parserhook", version: "0.8.3" },
    { name: "RSS feed", type: "parserhook", version: "2.25.1" },
    { name: "UserFunctions", type: "parserhook", version: "2.8.1" },
    { name: "UrlGetParameters", type: "parserhook", version: "1.6.0" },
    { name: "AddHTMLMetaAndTitle", type: "parserhook", version: "0.7" },
    { name: "CharInsert", type: "parserhook", version: null },
    { name: "YouTube", type: "parserhook", version: "1.9.3" },
    { name: "Josa", type: "parserhook", version: "0.2.0" },
    { name: "Babel", type: "parserhook", version: "1.12.0" },
    { name: "CSS", type: "parserhook", version: "3.5.0" },
    { name: "DynamicPageList3", type: "parserhook", version: "3.3.8" },
    { name: "DPLforum", type: "parserhook", version: "3.7.2" },
    { name: "LogoFunctions", type: "parserhook", version: "2.1" },
    { name: "RandomSelection", type: "parserhook", version: "2.3.0" },
    { name: "RandomImage", type: "parserhook", version: "1.5.1" },
    { name: "Spoilers", type: "parserhook", version: "2.2.3" },
    { name: "Scribunto", type: "parserhook", version: null },
    { name: "SimpleTooltip", type: "other", version: "1.1.0" },
    { name: "Gadgets", type: "other", version: null },
    { name: "LocalisationUpdate", type: "other", version: "1.4.0" },
    { name: "MultimediaViewer", type: "other", version: null },
    { name: "OATHAuth", type: "other", version: "0.5.0" },
    { name: "Thanks", type: "other", version: "1.2.0" },
    { name: "MobileFrontend", type: "other", version: "2.4.0" },
    { name: "TextExtracts", type: "other", version: null },
    { name: "Popups", type: "other", version: null },
    { name: "DismissableSiteNotice", type: "other", version: "1.0.1" },
    { name: "Highly Automated Welcome Tool", type: "other", version: "0.8.3" },
    { name: "RevisionSlider", type: "other", version: null },
    { name: "SandboxLink", type: "other", version: null },
    { name: "TwoColConflict", type: "other", version: null },
    { name: "CommonsMetadata", type: "other", version: null },
    { name: "WikiLove", type: "other", version: "1.3.1" },
    { name: "WikibaseClient", type: "wikibase", version: null },
    { name: "MonoBook", type: "skin", version: null },
    { name: "Timeless", type: "skin", version: "0.9.1" },
    { name: "Vector", type: "skin", version: "1.0.0" },
    { name: "Cologne Blue", type: "skin", version: null },
    { name: "Modern", type: "skin", version: null },
    { name: "MinervaNeue", type: "skin", version: null },
    { name: "CiteThisPage", type: "specialpage", version: null },
    { name: "Global Usage", type: "specialpage", version: "2.2.0" },
    { name: "Interwiki", type: "specialpage", version: "3.2" },
    { name: "CreatedPagesList", type: "specialpage", version: "1.2.1" },
    { name: "Echo", type: "specialpage", version: null },
    { name: "Poll", type: "specialpage", version: "2.0" },
    { name: "Contributors", type: "specialpage", version: "2.0" },
    { name: "MassMessage", type: "specialpage", version: "0.4.0" },
    { name: "CheckUser", type: "specialpage", version: "2.5" },
    { name: "DeleteBatch", type: "specialpage", version: "1.8.1" },
    { name: "Newest Pages", type: "specialpage", version: "1.22" },
    { name: "Nuke", type: "specialpage", version: null },
    { name: "Replace Text", type: "specialpage", version: "1.7" },
    { name: "Renameuser", type: "specialpage", version: null },
    { name: "RefreshSpecial", type: "specialpage", version: "1.6.0" },
    { name: "TemplateSandbox", type: "specialpage", version: "1.1.0" },
    { name: "Editcount", type: "specialpage", version: null },
    { name: "UserMerge", type: "specialpage", version: "1.10.1" },
    { name: "MassEditRegex", type: "specialpage", version: "8.4.1" },
    { name: "CodeEditor", type: "editor", version: null },
    { name: "WikiEditor", type: "editor", version: "0.5.3" },
    { name: "CodeMirror", type: "editor", version: "4.0.0" },
    { name: "PDF Handler", type: "media", version: null },
    { name: "TimedMediaHandler", type: "media", version: "0.6.0" },
    { name: "SpamBlacklist", type: "antispam", version: null },
    { name: "SmiteSpam", type: "antispam", version: "0.4" },
    { name: "TitleBlacklist", type: "antispam", version: "1.5.0" },
    { name: "Antispam by CleanTalk", type: "antispam", version: "2.3" },
    { name: "ConfirmEdit", type: "antispam", version: "1.6.0" },
    { name: "ReCaptchaNoCaptcha", type: "antispam", version: null },
    { name: "Abuse Filter", type: "antispam", version: null },
    { name: "PageImages", type: "api", version: null }
  ],
  extensionTags: [
    "pre",
    "nowiki",
    "gallery",
    "indicator",
    "langconvert",
    "css",
    "embedvideo",
    "evlplayer",
    "vplayer",
    "archiveorg",
    "bambuser",
    "bambuser_channel",
    "beam",
    "disclose",
    "blip",
    "bing",
    "collegehumor",
    "dailymotion",
    "divshare",
    "facebook",
    "funnyordie",
    "gfycat",
    "jwplayer",
    "kickstarter",
    "mediacccde",
    "metacafe",
    "microsoftstream",
    "mixer",
    "nico",
    "rutube",
    "smashcast",
    "soundcloud",
    "spotifyalbum",
    "spotifyartist",
    "spotifytrack",
    "teachertube",
    "ted",
    "tubitv",
    "tudou",
    "tvpot",
    "twitch",
    "twitchclip",
    "twitchvod",
    "videomaten",
    "vimeo",
    "vine",
    "yahoo",
    "youtube",
    "youtubeplaylist",
    "youtubevideolist",
    "youku",
    "source",
    "syntaxhighlight",
    "templatestyles",
    "math",
    "chem",
    "rss",
    "seo",
    "aovideo",
    "aoaudio",
    "wegame",
    "tangler",
    "gtrailer",
    "nicovideo",
    "dpl",
    "dynamicpagelist",
    "forum",
    "choose",
    "randomimage",
    "spoiler",
    "categorytree",
    "ref",
    "references",
    "imagemap",
    "inputbox",
    "poem",
    "charinsert"
  ],
  functionHooks: [
    "ns",
    "nse",
    "urlencode",
    "lcfirst",
    "ucfirst",
    "lc",
    "uc",
    "localurl",
    "localurle",
    "fullurl",
    "fullurle",
    "canonicalurl",
    "canonicalurle",
    "formatnum",
    "grammar",
    "gender",
    "plural",
    "bidi",
    "numberofpages",
    "numberofusers",
    "numberofactiveusers",
    "numberofarticles",
    "numberoffiles",
    "numberofadmins",
    "numberingroup",
    "numberofedits",
    "language",
    "padleft",
    "padright",
    "anchorencode",
    "defaultsort",
    "filepath",
    "pagesincategory",
    "pagesize",
    "protectionlevel",
    "protectionexpiry",
    "namespace",
    "namespacee",
    "namespacenumber",
    "talkspace",
    "talkspacee",
    "subjectspace",
    "subjectspacee",
    "pagename",
    "pagenamee",
    "fullpagename",
    "fullpagenamee",
    "rootpagename",
    "rootpagenamee",
    "basepagename",
    "basepagenamee",
    "subpagename",
    "subpagenamee",
    "talkpagename",
    "talkpagenamee",
    "subjectpagename",
    "subjectpagenamee",
    "pageid",
    "revisionid",
    "revisionday",
    "revisionday2",
    "revisionmonth",
    "revisionmonth1",
    "revisionyear",
    "revisiontimestamp",
    "revisionuser",
    "cascadingsources",
    "int",
    "special",
    "speciale",
    "tag",
    "formatdate",
    "displaytitle",
    "pagesinnamespace",
    "multimaps",
    "simple-tooltip",
    "tip-text",
    "simple-tooltip-info",
    "tip-info",
    "simple-tooltip-img",
    "tip-img",
    "ev",
    "evt",
    "evp",
    "evu",
    "evl",
    "vlink",
    "var",
    "varexists",
    "var_final",
    "vardefine",
    "vardefineecho",
    "ifanon",
    "ifblocked",
    "ifsysop",
    "ifingroup",
    "username",
    "realname",
    "nickname",
    "useremail",
    "ip",
    "urlget",
    "contributors",
    "target",
    "Eul/Ruel",
    "Eun/Neun",
    "E/Ga",
    "Gwa/Wa",
    "A/Ya",
    "Euro/Ro",
    "E/",
    "babel",
    "css",
    "dpl",
    "dplnum",
    "dplvar",
    "dplreplace",
    "dplchapter",
    "dplmatrix",
    "forumlink",
    "setlogo",
    "stamplogo",
    "choose",
    "spoiler",
    "invoke",
    "noexternallanglinks",
    "property",
    "statements",
    "commaSeparatedList",
    "categorytree",
    "if",
    "ifeq",
    "switch",
    "ifexist",
    "ifexpr",
    "iferror",
    "time",
    "timel",
    "expr",
    "rel2abs",
    "titleparts",
    "len",
    "pos",
    "rpos",
    "sub",
    "count",
    "replace",
    "explode",
    "urldecode"
  ],
  variables: [
    "!",
    "=",
    "currentmonth",
    "currentmonth1",
    "currentmonthname",
    "currentmonthnamegen",
    "currentmonthabbrev",
    "currentday",
    "currentday2",
    "currentdayname",
    "currentyear",
    "currenttime",
    "currenthour",
    "localmonth",
    "localmonth1",
    "localmonthname",
    "localmonthnamegen",
    "localmonthabbrev",
    "localday",
    "localday2",
    "localdayname",
    "localyear",
    "localtime",
    "localhour",
    "numberofarticles",
    "numberoffiles",
    "numberofedits",
    "articlepath",
    "pageid",
    "sitename",
    "server",
    "servername",
    "scriptpath",
    "stylepath",
    "pagename",
    "pagenamee",
    "fullpagename",
    "fullpagenamee",
    "namespace",
    "namespacee",
    "namespacenumber",
    "currentweek",
    "currentdow",
    "localweek",
    "localdow",
    "revisionid",
    "revisionday",
    "revisionday2",
    "revisionmonth",
    "revisionmonth1",
    "revisionyear",
    "revisiontimestamp",
    "revisionuser",
    "revisionsize",
    "subpagename",
    "subpagenamee",
    "talkspace",
    "talkspacee",
    "subjectspace",
    "subjectspacee",
    "talkpagename",
    "talkpagenamee",
    "subjectpagename",
    "subjectpagenamee",
    "numberofusers",
    "numberofactiveusers",
    "numberofpages",
    "currentversion",
    "rootpagename",
    "rootpagenamee",
    "basepagename",
    "basepagenamee",
    "currenttimestamp",
    "localtimestamp",
    "directionmark",
    "contentlanguage",
    "pagelanguage",
    "numberofadmins",
    "cascadingsources",
    "choose",
    "noexternallanglinks",
    "wbreponame"
  ]
};
